# Generated by Django 6.1 on 2026-08-15 23:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Действие (например, «выходить на прогулку»)', max_length=255)),
                ('place', models.CharField(blank=True, help_text='Место выполнения', max_length=255)),
                ('time', models.TimeField(help_text='Время выполнения (например, 19:00)')),
                ('is_pleasant', models.BooleanField(default=False, help_text='Приятная привычка (вознаграждение)')),
                ('reward', models.CharField(blank=True, help_text='Вознаграждение текстом', max_length=255)),
                ('period_days', models.PositiveIntegerField(default=1, help_text='Периодичность в днях')),
                ('duration_seconds', models.PositiveIntegerField(help_text='Ожидаемое время выполнения в секундах')),
                ('is_public', models.BooleanField(default=False, help_text='Публичность привычки')),
                ('linked_habit', models.ForeignKey(blank=True, help_text='Связанная приятная привычка', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_habits', to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
