# Generated by Django 6.1 on 2026-08-15 23:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habit',
            options={'ordering': ['-created_at'], 'verbose_name': 'привычка', 'verbose_name_plural': 'привычки'},
        ),
        migrations.RemoveField(
            model_name='habit',
            name='time',
        ),
        migrations.AddField(
            model_name='habit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='habit',
            name='time_of_day',
            field=models.TimeField(blank=True, help_text='Когда выполнять привычку', null=True, verbose_name='время выполнения'),
        ),
        migrations.AddField(
            model_name='habit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='habit',
            name='action',
            field=models.CharField(help_text='Я буду [ДЕЙСТВИЕ]...', max_length=255, verbose_name='действие'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=60, help_text='Предполагаемое время выполнения привычки в секундах', verbose_name='время на выполнение (сек)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_pleasant',
            field=models.BooleanField(default=False, help_text='Если True — это вознаграждение, а не полезная привычка', verbose_name='приятная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='публичная привычка'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='linked_habit',
            field=models.ForeignKey(blank=True, help_text='Только для полезных привычек: приятная привычка как вознаграждение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_from', to='habits.habit', verbose_name='связанная привычка (приятная)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='period_days',
            field=models.PositiveIntegerField(default=1, help_text='Как часто повторять привычку (в днях)', verbose_name='периодичность (дней)'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='place',
            field=models.CharField(blank=True, max_length=255, verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='habit',
            name='reward',
            field=models.CharField(blank=True, help_text='Чем наградить себя после выполнения (если не используется связанная привычка)', max_length=255, verbose_name='вознаграждение'),
        ),
    ]
